### ISSUE TITLE
Getting Error When Running Gulp

### ISSUE THREAD

**Issue by realph** [niksy/throttle-debounce#1]
I'm getting this error when running `gulp`.

```
Error: Cannot find module 'browserify-shim' from '/Users/realph/Desktop/jekyll/node_modules/throttle-debounce'
```

I'm requiring it, just like the README:

```
var td = require('throttle-debounce');
```

Any reason why this is happening?

**Comment by niksy** [comment]
Hm, strange, I haven’t tried it on projects without browserify-shim so I haven’t encountered this error. I have browserify-shim as dev dependancy in this module so it won’t be installed when installing from npm by default.

Easiest way to have it be required as it should is to install browserify-shim as dev dependancy in your project and it should be picked up as usual. But maybe I should revise this module and remove browserify-shim as dependancy altogether and leave shimming on per project basis (or move browserify-shim to standard dependancy).

**Comment by niksy** [comment]
@realph I’ve pushed new version which applies browserify-shim only for standalone build. Shimming is there only because standalone builds don’t pack whole jQuery but expect it to already be available in global namespace. For every CommonJS build process (Browserify, Webpack, etc.) developers should take care to partialize their bundles (I suppose you already do this as part of bundling process).

Can you confirm that it’s working now?

**Comment by alexgorbatchev** [comment]
This module doesn't seem to be meant to work outside of browser/jquery environment, which is a shame since there's absolutely no reason to tie this to jquery. It should really export proper functions and let consumer decide how and where to bolt them onto if there's a need.

> For convenience, standalone version is also provided and it maps to jQuery namespace if it exists, otherwise it adds two methods to global (window) namespace.

**Comment by niksy** [comment]
Hey @alexgorbatchev, sorry for super late reply!

I’ve just pushed new major release which remove jQuery as dependancy, doesn’t rely on Browserify and shimming and works as standard CommonJS module. Hope this solves your issue!
