### ISSUE TITLE
Typescript typings do not work properly

### ISSUE THREAD

**Issue by plee-nm** [niksy/throttle-debounce#14]
The typings that were added in 2.0 now can cause compiler errors in typescript projects.

```
throttle(300, function () {
    // Throttled function
}); 
```

`TS2345: Argument of type '() => void' is not assignable to parameter of type 'boolean'.`

**Comment by niksy** [comment]
@plee-nm what is your suggestion? I’m willing to implement TS-related stuff based on PR.

**Comment by plee-nm** [comment]
I would recommend removing the types and putting them on an external typings service so they can be treated as a first class citizen.  

If you want to have them locally I would write some tests along with the definition.  I was able to get the throttle definition working by overloading the function definition.  I did not test out the debounce function.

```ts
export function throttle(delay: number, noTrailing?: boolean, callback?: Function, debounceMode?: boolean): Function;

export function throttle(delay: number, callback: Function, debounceMode?: boolean): Function;

export function debounce(delay: number, atBegin: boolean, callback?: Function): Function;
```

It gets a little tricky since a callback is required but it can be after the `noTrailing` argument and in typescript it (deservedly so) does not allow a required parameter after an optional parameter.

**Comment by niksy** [comment]
> I would recommend removing the types and putting them on an external typings service so they can be treated as a first class citizen.

@plee-nm can you submit PR with proposed changes?

**Comment by plee-nm** [comment]
https://github.com/niksy/throttle-debounce/pull/15

**Comment by plee-nm** [comment]
@niksy There anything you need extra on the PR?  Is this going to get merged soon?

**Comment by plee-nm** [comment]
@niksy Is there anything else you need?  My latest build has been broken for almost 2 weeks now and I thought this would have been merged by now.

**Comment by niksy** [comment]
Sorry for late delay @plee-nm :( Will push new version soon!
