### ISSUE TITLE
Debounce not working

### ISSUE THREAD

**Issue by Argeare5** [niksy/throttle-debounce#23]
Why debounce not working?

My code 
import React from 'react'
import { BaseTextField } from '../../common/form-fields'
import queryString from 'query-string'
import { debounce } from 'throttle-debounce'

import { staticStyles } from './style'

class SearchPanel extends React.Component {

  constructor(props) {
    super(props)
    const query = queryString.parse(props.location.search)
    this.state = { search: query.search || '" }
  }

  handleSearchChange = e => {
    e.preventDefault()
    const query = queryString.parse(this.props.location.search)
    const search = e.target.value
    this.setState({ search })
    query.search = search || undefined
    query.page = 1
    this.props.history.replace({
      ...this.props.location,
      search: queryString.stringify(query)
    })
    debounce(1000, () => this.props.getList(query))
  }

  render() {
    return (
      <div className="SearchPanel">
         <div className="SearchPanel__input-inner">
           <BaseTextField
             type="text"
             name="search"
             textId="justSearch"
             onChange={this.handleSearchChange}
             value={this.state.search} />
         </div>
      </div>
    );
  }
}

export default SearchPanel

**Comment by niksy** [comment]
Do you have small test case available somewhere?

**Comment by Argeare5** [comment]
as I understood, this debounce can not be inside a function and just can not perform a function, right?

**Comment by niksy** [comment]
If I’m looking at your code correctly, debounce should be applied on `handleSearchChange` function, not function inside that function.

**Comment by Argeare5** [comment]
as I understood it is possible and inside the function, but it is necessary to call it, and I did not notice at once))

type is
debounce(1000, () => this.props.getList(this.query))()

I'm sorry to trouble you
