### ISSUE TITLE
Throttling doesn't work. 

### ISSUE THREAD

**Issue by dustinbarnes** [niksy/throttle-debounce#27]
I'm 100% sure this is developer error, but I can't figure it out... 

I have a simple nodejs setup like this: 

```
const debounce = require('throttle-debounce').debounce;

function createExpensiveThing() {
    console.log("called this thing");
    debounce(50, true, () => {
        console.log("throttled called!");
    });
}

setInterval(createExpensiveThing, 100);
```

And the output: 

```
$ node --version
v11.6.0
$ node throttle-test.js
called this thing
called this thing
called this thing
called this thing
called this thing
called this thing
```

At no point does the "throttled called!" message appear in the output. The function never fires. What am I missing here?

**Comment by niksy** [comment]
I think you need to debounce `createExpensiveThing`:

```js
setInterval(debounce(50, createExpensiveThing), 100);
```

**Comment by dustinbarnes** [comment]
Yes, that was the key. The debounce gave me an object I was ignoring, when it was the function wrapper I needed. Thanks for the insight.
