### ISSUE TITLE
The cancel() method prevents all future invocations

### ISSUE THREAD

**Issue by appden** [niksy/throttle-debounce#28]
The docs and comments imply this is might not by design, but if it is intended then perhaps the readme can be clarified.

Documentation makes this a little unclear...
> The logic that is being throttled or debounced will no longer be called.

The comment in the source code implies only the timeout is being canceled..
> Function to cancel next exec

Thanks!

**Comment by renekliment** [comment]
+1 for this

Also, it would be great if there was a parameter to the `.cancel()`, so we could cancel either only the current series or all series including the future. Does that make sense?

What bugs me is that I believe `.cancel()` should just cancel the current series and something like `.cancel(true)` should cancel the whole thing, but that would be a BC break :-/

**Comment by kesha-antonov** [comment]
Same here

**Comment by niksy** [comment]
Ah, I see - `cancel` cancels all future invocations, but what is preferred is cancelling only current invocation, which is how it’s documented in README.

I would definitely be willing to accept PR for this!

**Comment by xbreid** [comment]
+1 for this as well. 

Wondering if anyone has a solid work around for this - to cancel current series, as well as future invocations.

**Comment by niksy** [comment]
This has been released in https://github.com/niksy/throttle-debounce/releases/tag/v5.0.0.

**Comment by 9mm** [comment]
awesome, thank you for this
