### ISSUE TITLE
`noTrailing` exegesis error

### ISSUE THREAD

**Issue by lishanggang** [niksy/throttle-debounce#31]
// `noTrailing` defaults to falsy. 

correct is `noTrailing` defaults to false.

**Comment by niksy** [comment]
Can you be more specific?

**Comment by niksy** [comment]
This defaults to `false` in latest version: https://github.com/niksy/throttle-debounce/blob/203deec24d78abf50751a48c10d0ca7ab1896806/throttle.js#L26
