### ISSUE TITLE
[Violation] 'setTimeout' handler took <some value>ms

### ISSUE THREAD

**Issue by yanickrochon** [niksy/throttle-debounce#33]
Google Chrome 58 and up do not hide these debug information anymore, and it makes this plugin spew a bunch of messages every time the throttled function takes longer to run. One suggestion would to delegate the handler outside of the `setTimeout`. using a `Promise` if available.

If the environment does not offer the implementation, then the error won't matter anyway, and a dumb placeholder can be used, something like

```js
if (!Promise) {
	Promise = {
		resolve: function () {
			return {
				then: function(handler) { handler(); );
			};
		}
	};
}
```

Then change [the `exec`](https://github.com/niksy/throttle-debounce/blob/6101e5221e494ad4a2bb97185b4ca96e7cd2f903/throttle.js#L69) function like so :

```js
function exec () {
	Promise.resolve().then(function () {
		lastExec = Date.now();
		callback.apply(self, args);
	});
}
```

**Comment by niksy** [comment]
Can you make the PR for this?

**Comment by niksy** [comment]
@yanickrochon is this still an issue? Can you provide more detailed example when does this error shows?

**Comment by yanickrochon** [comment]
Havan't seen it in other projects after reporting this. I presume this can be closed, sure!
