### ISSUE TITLE
Usage example doesn't show well the basic functionality

### ISSUE THREAD

**Issue by synchronos-t** [niksy/throttle-debounce#35]
I believe the usage example on the README needs to be better. Now for throttling the example is as follows:
```
throttle(300, () => {
    // Throttled function
});
```

One would assume that those lines alone would execute what's there at the `// Throttled function`. This, however, yet doesn't execute anything. The `throttle()` call here just returns the throttled function, but in the example it's just lost as it isn't assigned anywhere, so it's not even a working example. The example just doesn't convey the fact that the `// Throttled function` means that the `throttle()` is _returning_ a throttled function, not executing it throttled, as the comment is there inside the inner function.

After understanding it, it's quite easy to see why it's working that way, but it isn't intuitive or easy at all to get when you first see the documentation.

To my understanding, the correct usage and a better annotated example would be:
```
const throttledFunction = throttle(300, () => {
    // The stuff that is expensive to execute
});

throttledFunction(); // Call as often as you like; the inner function is executed only every 300ms
```

Or something along those lines. And something similar, of course, for debouncing as well.

I believe this lack of a working minimal example is, e.g., a reason why the issue #16 was filed in the first place, as the code provided uses the `debounce()` in the same way that the function it's returning is just lost, as it's not assigned anywhere.

**Comment by niksy** [comment]
Yeah, I can see how this can be misleading. Would you be willing to open PR for this?

**Comment by itboos** [comment]
@niksy @synchronos-t  hi ~, I create a PR for this,  see [#36 ](https://github.com/niksy/throttle-debounce/pull/36)

**Comment by niksy** [comment]
@synchronos-t @itboos added some useful explanation to README. If you see anything missing or misleading, please open new issue.
