### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by stevebaxter** [niksy/throttle-debounce#39]
What is the license for this project? LICENSE.md seems to include multiple licenses, it's not clear what we have to do for attribution:

https://github.com/niksy/throttle-debounce/blob/master/LICENSE.md

**Comment by niksy** [comment]
@stevebaxter https://github.com/niksy/throttle-debounce#license

Basically, MIT.

**Comment by stevebaxter** [comment]
Thanks, there's a GPL license there as well which would obviously be a big problem. This is being picked up by oss-attribution-generator (https://www.npmjs.com/package/oss-attribution-generator) as both.

No problem, if you can can confirm it's MIT then we are good!
