### ISSUE TITLE
Add min version to "main" in bower.json

### ISSUE THREAD

**Issue by likerRr** [niksy/throttle-debounce#4]
Please, make "main" option in bower.json array and include minified version:
https://github.com/niksy/throttle-debounce/blob/master/bower.json#L10

It's useful for plugins like https://www.npmjs.com/package/main-bower-files

**Comment by niksy** [comment]
He @likerRr, sorry for super late reply! :(

Newest version of this module remove Bower support, and as for minified version, [Bower spec recommends not to define minified files as entry points](https://github.com/bower/spec/blob/master/json.md#main).

Hope you’ve managed to solve this issue in the meantime!
