### ISSUE TITLE
Dual license of MIT/GPL

### ISSUE THREAD

**Issue by thinh-nd** [niksy/throttle-debounce#40]
Hi, I saw in the license file that this module license is dual license under MIT and GPL. I just want to confirm is this module is dual license under **BOTH** MIT and GPL, or does it dual license under MIT **OR** GPL, meaning I can select either of them?

**Comment by niksy** [comment]
The original code is MIT/GPL, this repository is MIT. I would go with MIT.

**Comment by agilgur5** [comment]
See also #64 + #65 now
