### ISSUE TITLE
doesn't work in react native

### ISSUE THREAD

**Issue by gentlee** [niksy/throttle-debounce#5]
store.subscribe(() => throttle(1000, () => other.saveState()));

other.saveState is not calling at all, while throttle is called many times

**Comment by niksy** [comment]
Sorry, I don’t have experience with React Native so I can’t really help you here. Have you tried with other arguments for that method?

**Comment by gentlee** [comment]
no, only that way. using `lodash` instead

**Comment by niksy** [comment]
Yeah, Lodash version seems like more resilient to environment changes. Closing this issue since you’ve found solution.

**Comment by alexandersandberg** [comment]
For future reference: This library works **perfectly fine** in React Native (tested with 0.63.0).
