### ISSUE TITLE
Update types for new version

### ISSUE THREAD

**Issue by niksy** [niksy/throttle-debounce#52]
Before we can release new version, we need to update types. They are hosted on https://github.com/DefinitelyTyped/DefinitelyTyped

@seiyab are you up for it?

**Comment by seiyab** [comment]
Yes.
I love TypeScript 👍

**Comment by niksy** [comment]
@seiyab OK, when you’re ready, I can publish new version of package, and then you can open PR on DefinitelyTyped!

**Comment by seiyab** [comment]
@niksy 
Here is diff I wrote. https://github.com/seiyab/DefinitelyTyped/pull/1
Would you like to review it?
- Yes -> I'll open PR on DefinitelyTyped after you accept.
- No -> I'll open PR on DefinitelyTyped.

I can add descriptions if you don't familiar with TS.

**Comment by niksy** [comment]
@seiyab no, this is good, you can open PR on DefinitelyTyped and they can review it. I will publish new release so types can land when DT team accepts them.

Thank you so much!
