### ISSUE TITLE
Normalize debounce API with throttle API changes

### ISSUE THREAD

**Issue by niksy** [niksy/throttle-debounce#53]
When we made changes to throttle API in version 4, incidentally we haven’t aligned those changes to debounce method.

@seiyab are you willing to make same changes to debounce API, along with type changes?

I think it would be great to have similar API for both methods (delay, callback and options).

**Comment by seiyab** [comment]
I will make same changes if users welcome the breaking changes and publishing another major update.

**Comment by niksy** [comment]
Yeah, this should be major update (unfortunately). No big deal, next time we will be more careful 😄

**Comment by seiyab** [comment]
OK, I will create PR 👍

**Comment by seiyab** [comment]
Here I did: https://github.com/niksy/throttle-debounce/pull/54
And I will draft a PR to DefinitelyTyped later.

**Comment by niksy** [comment]
@seiyab thanks for the great work. This is now merged so we need updated types.
