### ISSUE TITLE
Throttle does not throttle on first call

### ISSUE THREAD

**Issue by yanickrochon** [niksy/throttle-debounce#55]
The following declearation does not do anything if the function is called only once :

```js
const t = throttle(100, () => {
  console.log("OK");
}, { noLeading:true });

t();   // will never output anything
```

Essentially, I am expecting throttle to call the function at least once every `100 ms` (in this case), but the function never gets called.

Using `debounce` won't work because, if the function is called many times, I want the function to throttle, not be debounced, but I don't want the function to be executed immediately; the first call should be debounced.

The current implementation is in error to me.

**Comment by niksy** [comment]
@seiyab do you have some input here?

**Comment by seiyab** [comment]
I reproduced it here.
https://codesandbox.io/s/muddy-monad-k7hx36?file=/src/index.js

Calling throttled-function just single time just skips leading call and doesn't schedule first call.
This behavior is confusing and we can call it bug.
I fix it.

**Comment by seiyab** [comment]
I'm sorry for the inconvenience 🙏  https://github.com/niksy/throttle-debounce/pull/56

**Comment by niksy** [comment]
This has been released in https://github.com/niksy/throttle-debounce/releases/tag/v4.0.1

Thanks @seiyab for fixing!
