### ISSUE TITLE
It is recommended that the change information of API be noted in the README.md file.

### ISSUE THREAD

**Issue by uovol** [niksy/throttle-debounce#57]
I have recently noticed that the API of this plug-in has changed, and it is recommended to add relevant instructions to the README.md file.

Because when I was browsing the code I used throttle-debounce earlier recently, I wanted to know the detailed usage of a parameter in github, only to find that the order of the parameters did not correspond. I went through the history to know that the API had changed.

**Comment by niksy** [comment]
What exactly is wrong in the documentation?

**Comment by uovol** [comment]
like this https://github.com/niksy/throttle-debounce/pull/58/files, This is one of my pull requests

This allows people like me who did not upgrade to the latest version to have a friendly tip and link.

**Comment by niksy** [comment]
Documentation always shows latest version, and backwards compatibility is achieved with major version bumps.
