### ISSUE TITLE
async debounce?

### ISSUE THREAD

**Issue by s0updev** [niksy/throttle-debounce#59]
Hi, how can I get it work with async await? And with `this` binding
Can we get like a wrapper with working with promises?
I need it for a search input in a vuejs project

**Comment by niksy** [comment]
This is a wrapper around generic functions so it works with async functions also.
You can use either arrow functions or `Function.prototype.bind` for keeping `this` context.

**Comment by s0updev** [comment]
@niksy here's a codepen example, I used Vue but I think it doesn't matter
 https://codepen.io/s0updev/pen/bGvBwQJ?editors=1011

**Comment by s0updev** [comment]
the one from [debounce-promise](https://github.com/bjoerge/debounce-promise) package does work btw

**Comment by niksy** [comment]
I think you can debounce `debouncedSearch` function and get the result you want.

```js
const methods = {
  debouncedSearch: debounce(300, async function(e) {
    let res = await this.fetchData();

    console.log(res, e.target.value);
  }),
  fetchData: async function() {
    let res = await fetch("https://api.github.com/orgs/");
    res = await res.json();

    return res;
  }
};
```

**Comment by s0updev** [comment]
But I need to debounce `fetchData` function, not the one that I assign to an event because it's a search input and it should be very responsive on each key press

**Comment by niksy** [comment]
This module doesn’t implement function return values, you can try with callbacks:

```js
const methods = {
  debouncedSearch(e) {
    this.debounce((res) => {
      console.log(res, e.target.value);
    });
  },
  debounce: debounce(300, async function (callback) {
    let res = await fetch("https://api.github.com/orgs/");
    res = await res.json();

    callback(res);
  })
};
```
