### ISSUE TITLE
Strange behaviour with React useState + debounce

### ISSUE THREAD

**Issue by pxtnpxtn** [niksy/throttle-debounce#61]
Hello!

I am trying to get debounce to work in my project. In the input's onChange, if it also contains a setState, then the debounce function stops working and instead prints out each key stroke individually. I'm wanting the setState to be there, because the value will come from localStorage, and the useState's value is used elsewhere in my app.

[https://codesandbox.io/s/adoring-nova-exxfwf?file=/src/App.js](https://codesandbox.io/s/adoring-nova-exxfwf?file=/src/App.js)

Any explanation on what is happening and how I can work around it would be much appreciated!

Thanks.

**Comment by niksy** [comment]
@pxtnpxtn is this similar to https://github.com/niksy/throttle-debounce/issues/47?

**Comment by Hades30** [comment]
wrapping the debounce function with useCallback fixed the problem , this happens because whenever a state changes , you are creating multiple debounce functions which is basically creating multiple callbacks with a delay.

**Comment by pxtnpxtn** [comment]
> wrapping the debounce function with useCallback fixed the problem , this happens because whenever a state changes , you are creating multiple debounce functions which is basically creating multiple callbacks with a delay.

That does make a lot of sense, thank you @Hades30. I wrapped it in a useCallback though and not doesn't seem to be logging anything at all. What am I missing?

```
const searchAddress = useCallback(() => {
    debounce(1000, (text) => {
      console.log("text==>", text);
      // Some API call
    });
  }, []);
```

[https://codesandbox.io/s/adoring-nova-exxfwf?file=/src/App.js](https://codesandbox.io/s/adoring-nova-exxfwf?file=/src/App.js)

**Comment by Hades30** [comment]
https://codesandbox.io/s/cocky-merkle-xvi09j?file=/src/App.js

**Comment by pxtnpxtn** [comment]
Thank you kindly @Hades30. Really appreciate your time.

For anyone in the future facing this issue:

```
const searchAddress = useCallback(
    debounce(1000, (text) => {
      console.log("text==>", text);
      // Some API call
    }),
    []
);
```
